global:
  hosts:
    domain: <domain>
  psql:
    host: <rds-host>
    password:
      secret: automation-library-gitlab-postgresql-password
    port: 5432
    database: gitlabhq_production
    username: gitlab
  ingress:
    # Disable cert-manager to use self-signed certificates for the backend
    configureCertmanager: false
    # Enable TLS termination on Ingress objects, by NGINX to use self-signed certificates 
    tls:
      enabled: true

certmanager-issuer:
  email: "<signer-email>"

certmanager:
  install: false

gitlab-runner:
  install: false
  
# see: https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/examples/aws/elb-layer7-loadbalancer.yaml
nginx-ingress:
  controller:
    config:
      # pass the X-Forwarded-* headers directly from the upstream
      use-forwarded-headers: "true"
    service:
      annotations:
        # Layer 7, injects X-Forwarded-* headers
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
        # Configure ACM certifiates
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:<region>:<account-id>:certificate/<certificate-id>
        # Configure which ports are to terminate SSL.
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https

postgresql:
  install: false